Repository TeamMotherlode/MotherlodeCore, pull requests merged in 2021-02, with the labels that each got.

#47 Updated to 21w06a
  build.gradle
  dependencies.gradle
  gradle.properties
  motherlode-base/src/main/java/motherlode/base/Motherlode.java
  motherlode-base/src/main/java/motherlode/base/api/woodtype/WoodType.java
  motherlode-base/src/main/java/motherlode/base/mixin/BlocksAccessor.java
  motherlode-biomes/src/main/java/motherlode/biomes/world/RuinedFlatsBiome.java
  motherlode-biomes/src/main/java/motherlode/biomes/world/feature/MarshFeature.java
  motherlode-building-blocks/src/main/java/motherlode/buildingblocks/block/DefaultPathBlock.java
  motherlode-redstone/src/main/java/motherlode/redstone/block/GrateBlock.java
  motherlode-redstone/src/main/java/motherlode/redstone/persistentstate/RedstoneChannelManager.java
  motherlode-spelunky/src/main/java/motherlode/spelunky/fluid/SlimeFluid.java
Labels: reviews needed, small change

#46 feat: update grate block to only allow items through
  motherlode-redstone/src/main/java/motherlode/redstone/MotherlodeRedstoneBlocks.java
  motherlode-redstone/src/main/java/motherlode/redstone/block/GrateBlock.java
  motherlode-redstone/src/main/resources/assets/motherlode-redstone/blockstates/steel_grate.json
  motherlode-redstone/src/main/resources/assets/motherlode-redstone/models/block/steel_grate.json
  motherlode-redstone/src/main/resources/assets/motherlode-redstone/models/block/steel_grate_opened.json
  motherlode-redstone/src/main/resources/assets/motherlode-redstone/textures/block/steel_grate.png
  motherlode-redstone/src/main/resources/assets/motherlode-redstone/textures/block/steel_grate_opened.png
Labels: enhancement, last call

#48 Updated to 21w08b
  dependencies.gradle
  gradle.properties
  motherlode-base/src/main/java/motherlode/base/Motherlode.java
  motherlode-base/src/main/java/motherlode/base/api/worldgen/FeaturesManager.java
  motherlode-base/src/main/java/motherlode/base/api/worldgen/MotherlodeOreBlock.java
  motherlode-biomes/src/main/java/motherlode/biomes/world/feature/MarshFeature.java
  motherlode-biomes/src/main/java/motherlode/biomes/world/feature/structure/CampGenerator.java
  motherlode-copper-dungeon/src/main/java/motherlode/copperdungeon/networking/ZapS2CPacket.java
  motherlode-materials/src/main/java/motherlode/materials/MotherlodeMaterialsBlocks.java
  motherlode-materials/src/main/java/motherlode/materials/world/GemTargets.java
  motherlode-redstone/src/main/java/motherlode/redstone/block/RedstoneTransmitterBlockEntity.java
  motherlode-redstone/src/main/java/motherlode/redstone/block/RedstoneTransmitterRenderer.java
  motherlode-redstone/src/main/java/motherlode/redstone/persistentstate/RedstoneChannelManager.java
Labels: last call
